name: Automatic PR Merger

on:
  push: {} # update PR when base branch is updated

jobs:
  # thats's all. single step is needed - if PR is mergeable according to
  # branch protection rules it will be merged automatically
  mergepal:
    runs-on: ubuntu-22.04
    if: github.repository == 'RasaHQ/rasa'

    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
      - uses: rasahq/update-pr-branch@f7012036a6d5659cfbc37f180716963511e81f95
        with:
          token: ${{ secrets.UPDATE_BRANCH_PAT }}
          # required parameter by original action -
          # check is already done through protected branches so not needed for us
          required_approval_count: 0
          # update branch despite failing check runs
          require_passed_checks: false
